### ISSUE TITLE
Is this really 2.4.0?

### ISSUE THREAD

**Issue by hufftheweevil** [srh/rethinkdb#2]
I can certainly appreciate you trying to get 2.4.0 for Windows working. But this doesn't appear to be 2.4.0. I downloaded the zip, and ran the executable, and it says it is 2.3.2. Moreover, the new `setWriteHook` is not a recognized function on tables.

![explorer_2020-03-08_15-36-53](https://user-images.githubusercontent.com/26534009/76169835-a748cc80-6152-11ea-8221-5598d9fb7a51.png)

**Comment by srh** [comment]
What the...  I'll take a look.

**Comment by srh** [comment]
The version number was generated incorrectly by some build process.  `setWriteHook` works just fine.  I tested this by downloading and running the binary from Github.

**Comment by hufftheweevil** [comment]
Sorry, my mistake - I had forgotten to update my client library as well.

**Comment by srh** [comment]
Thanks for the notice, anyway.  I added a note about the version number in the release description.
